

#set-option -g default-shell /bin/zsh
set-option -g default-shell /bin/fish

set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:color=256'

set -g prefix C-q
unbind C-b
unbind Enter


set-option -g status-position top

set-option -g status-left-length 90
set-option -g status-right-length 90

set-option -g status-left '#[fg=cyan,bg=#303030]#{?client_prefix,#[reverse],} tmux #H:[#P] #[default]'
set-option -g status-right '[%y-%m-%d(%a) %H:%M]'

set-option -g status-interval 1
set-option -g status-justify centre
set -g status-fg white
set -g status-bg black


bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind | split-window -h
bind - split-window -v

set-option -g base-index 1

set -g mouse on
set-window-option -g mouse on

setw -g mode-keys vi


bind-key C-p paste-buffer
