
[[plugins]]
repo = 'Shougo/dein.vim'


#=================================
# Theme
#=================================

[[plugins]]
repo = 'tomasr/molokai'
#hook_add = '''
#        colorscheme molokai
#        '''

[[plugins]]
repo = 'joshdick/onedark.vim'
#hook_add = '''
#        colorscheme onedark
#        '''

[[plugins]]
repo = 'rakr/vim-one'
# # hook_add = '''
#         colorscheme one
#         '''

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'jacoborus/tender.vim'
#hook_add = '''
#        colorscheme tender
#        '''

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
        colorscheme gruvbox
        '''


#=======================================

[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = '''
        let g:cheatsheet#cheat_file = '~/.config/nvim/.cheatsheet.md'
'''


[[plugins]]
repo = 'tyru/eskk.vim'



[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
        let g:lightline = {
        \ 'enable' : {'tabline': 0},
        \ 'colorscheme' : 'onedark',
        \ 'active' : {
        \       'left': [ ['mode', 'paste'], ['readonly', 'filename', 'modified'] ],
        \       'right': [ ['cocstaus'], ['percent', 'lineinfo'], ['charcode','fileformat','fileencoding', 'filetype'] ],
        \       },
        \
        \ 'component_function': {
        \        'cocstatus': 'coc#status',
        \        },
        \}
'''





[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
        let g:deoplete_enable_at_startup = 1
        let g:deoplete_disable_auto_complete = 1
        let g:deoplete#enable_smart_case = 1
        let g:deoplete#min_syntax_length = 3
        let g:deoplete#auto_complete_delay = 0
        let g:deoplete#enable_camel_case = 0
        let g:deoplete#enable_ignore_case = 0
        let g:deoplete#enable_refresh_always = 0
        let g:deoplete#file#enable_buffer_path = 1
        let g:deoplete#max_list = 10000
        inoremap <expr><tab> pumvisible() ? "\<C-n>" :
                \neosnippet#expandable_or_jumpable() ?
                \ "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
        inoremap <expr><BS> deoplete#smart_close_popup()."\<C-h>"
        inoremap <expr><CR> pumvisible() ? "\<C-y>" :"\<CR>"
        '''

[[plugins]]
repo = 'Shougo/neosnippet'
hook_add = '''
        let g:neosnippet#snippets_directory='~/.config/nvim/my_snippet'
        imap <C-k> <Plug>(neosnippet_expand_or_jump)
        imap <expr><tab> pumvisible() ? "\<C-n>" :
                \neosnippet#expandable_or_jumpable() ?
                \ "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
        '''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'junegunn/fzf.vim'
on_cmd = [
        'Files',
        'ProjectFiles',
        'Buffers',
        'BLines',
        'Historu',
        'Tags',
        'BTags',
        'GFiles',
        'Ag',
]
hook_add = '''
        set rtp+=~/.fzf
        set shell=/usr/bin/zsh
        nnoremap <silent> ,a :<C-u>Ag<CR>
        nnoremap <silent> ,f :<C-u>Files<CR>
        nnoremap <silent> ,b :<C-u>Buffers<CR>
        nnoremap <silent> ,m :<C-u>History<CR>
'''


[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add ='''
        nnoremap <C-n> :NERDTreeToggle<CR>
'''



[[plugins]]
repo = 'vim-scripts/Changed'


[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
        let g:ale_lint_on_text_cahnged = 'never'
        let g:ale_lint_on_insert_leave = 0
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'



[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'


[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'machakann/vim-highlightedyank'



