
[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'tomasr/molokai'
#hook_add = '''
#        colorscheme molokai
#        '''

[[plugins]]
repo = 'joshdick/onedark.vim'
#hook_add = '''
#        colorscheme onedark
#        '''

[[plugins]]
repo = 'rakr/vim-one'
# # hook_add = '''
#         colorscheme one
#         '''

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'jacoborus/tender.vim'
#hook_add = '''
#        colorscheme tender
#        '''

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
        colorscheme gruvbox
        '''




[[plugins]]
repo = 'tyru/eskk.vim'



[[plugins]]
repo = 'itchyny/lightline.vim'



[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
        let g:deoplete_enable_at_startup = 1
        let g:deoplete_disable_auto_complete = 1
        let g:deoplete#enable_smart_case = 1
        let g:deoplete#min_syntax_length = 3
        let g:deoplete#auto_complete_delay = 0
        let g:deoplete#enable_camel_case = 0
        let g:deoplete#enable_ignore_case = 0
        let g:deoplete#enable_refresh_always = 0
        let g:deoplete#file#enable_buffer_paht = 1
        let g:deoplete#max_list = 10000
        inoremap <expr><tab> pumvisible() ? "\<C-n>" :
                \neosnippet#expandable_or_jumpable() ?
                \ "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
        inoremap <expr><BS> deoplete#smart_close_popup()."\<C-h>"
        
        '''

[[plugins]]
repo = 'Shougo/neosnippet'
hook_add = '''
        let g:neosnippet#snippets_directory='~/.config/nvim/my_snippet'
        imap <C-k> <Plug>(neosnippet_expand_or_jump)
        imap <expr><tab> pumvisible() ? "\<C-n>" :
                \neosnippet#expandable_or_jumpable() ?
                \ "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
        '''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'


[[plugins]]
repo = 'Shougo/denite.nvim'



[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'vim-scripts/Changed'


[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'machakann/vim-highlightedyank'
